### ISSUE TITLE
ES6/Modern JS

### ISSUE THREAD

**Issue by JZL** [misterGF/echo#5]
This isn't a huge deal but, for a beginning user with a non-updated nodejs version, it will return an error because of the `=>` notation. You could simply change the required node version in the package.json but, because it's a one file package, I think it would be nice to include a non-modern JS file and/or a note in the README. 

Also, because it is a simpler JS package and mostly seems to use ES6 for some syntactic sugar, it could also be possible to set up a small CI integration which converted the ES6 -> normal JS and allow for it to be truly (and easily) across all node.js versions. I can submit a PR if you'd like.

**Comment by misterGF** [comment]
Thanks for the feedback. That makes sense. I'd love to see a PR.

**Comment by JZL** [comment]
Are you okay with travis as a CI (it could also be a Makefile to compile or a gulp/grunt taskrunner but it's sort of overkill)

**Comment by misterGF** [comment]
Yes I'm fine with travis. Haven't had the pleasure of working with travis yet. Looking forward to it.

**Comment by hobbyexplorer** [comment]
Hi Folks, Didn't see you guys are talking about the same here! 
I just finished submitting a basic travis setup PR here: #6 
@JZL  But it does not address the issue you mentioned(ES6 -> normal JS). 
I would leave that upto you!
